# Generated by Django 5.2.6 on 2025-11-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_last_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
