# Generated by Django 5.2.6 on 2025-11-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
