# Generated by Django 5.2.6 on 2025-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
