# Generated by Django 5.2.6 on 2025-12-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_userregistration_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photo/profile_picture'),
        ),
    ]
