# Generated by Django 5.2.6 on 2026-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_userregistration_is_active_userregistration_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
