# Generated by Django 5.2.6 on 2026-01-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookstoremodel_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='is_order',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bookstoremodel',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
