# Generated by Django 5.2.6 on 2026-01-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_bookstoremodel_is_order_bookstoremodel_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
