# Generated by Django 5.2.6 on 2026-01-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_bookstoremodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='book.userregistration'),
        ),
    ]
