# Generated by Django 5.2.6 on 2026-01-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_bookstoremodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstoremodel',
            name='owner',
        ),
    ]
