# Generated by Django 5.2.6 on 2026-01-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
