# Generated by Django 5.2.6 on 2026-01-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_bookstoremodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
