# Generated by Django 5.2.6 on 2026-01-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_category_cate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cate_image',
            new_name='category_image',
        ),
    ]
